# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Tyler Himes
description: "Greetings! I'm Tyler - a Data Scientist showcasing a collection of compelling projects in my portfolio. With a keen focus on driving tangible business impact, I invite you to explore my GitHub and LinkedIn profiles (or download my Resume) using the links provided below. Let's connect and delve into the world of data science!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Utah, USA"
resume_url: /docs/Resume.pdf
avatar_image: /img/square_image.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/tyler-himes/" # Add your linkedln handle
github: "https://github.com/tylerhimes"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

